#!/bin/bash
function create_invoice {
    input=$1
    echo "# Creating invoice with $input" >&2
    python src/invoice.py < $input
}

INPUT=$1
if [[ $1 ]]; then
    INPUT=$1;
else
    echo "No input file provided." >&2;
    exit 1;
fi;

create_invoice $INPUT;
