#!/usr/bin/env python
#-*- coding: utf-8 -*-

import argparse
from envois import invoice
import json
import sys

if __name__ == '__main__':
    try:
        fin = open(sys.argv[1], 'r')
    except:
        fin = sys.stdin
    print(invoice.main(fin))


