#!/usr/bin/env python
#-*- coding: utf-8 -*-

import json
import os
import sys
from argparse import ArgumentParser
sys.path.append('../envois')
from envois import invoice

if __name__ == '__main__':

    #set up argument parsing
    parser = ArgumentParser()
    parser.add_argument("-f", "--file", metavar="INPUT_FILE", type=str,
                        help="the json file used to generate invoice")
    parser.add_argument("-l", "--latex", action='store_true', default=False,
                        help="use latex template to render invoice, \
                        default is to use html")
    parser.add_argument("-o", metavar="OUTPUT_FILE", default="none",
                        help="output file name, default is printing to stdout")
    
    args = parser.parse_args()

    #TODO handle file inteligently based on working dir
    #selecting input source
    if args.file!=None:
        try:
            fin = open(args.file, 'r')
        except:
            print('unable to open specified file %s' % args.file)
            sys.exit()
    else:
        fin = sys.stdin
        
    invoice.main(inp=fin, latex=args.latex, outp=args.o)
